### ISSUE TITLE
Toggle button in list categories

### ISSUE THREAD

**Issue by sharanp98** [sharanp98/MaskRCNN#2]
After displaying the list of detected objects, the user must be able to select and deselect items with a **toggle button**
References:
https://stackoverflow.com/questions/3047755/i-am-trying-to-make-a-simple-toggle-button-in-javascript
https://www.w3schools.com/howto/howto_css_switch.asp

**Comment by Vivek760** [comment]
Fixed the issue by making some changes in the js file (ListCategories.js) @sharanp98
