### ISSUE TITLE
Disable 'Get Your Categories'

### ISSUE THREAD

**Issue by sharanp98** [sharanp98/MaskRCNN#3]
The 'Get Your Categories' button must not be allowed to be clicked more than once as it generates reads from the file and generates the list each time.

Task: Disable the button after it has been clicked once.

Reference: https://stackoverflow.com/questions/17114825/how-to-disable-button-after-one-click-with-validation-using-javascript

**Comment by Vivek760** [comment]
I've done some changes in it and fixed it. Added the code mentioned below:
`document.getElementById("getcategories").style.visibility= 'hidden'`
